[package]
name = "359forever/opencode"
version = "0.1.8"
description = "OpenCode Free Model Proxy on Wasmer Edge"

[dependencies]
"wasmer/winterjs" = "^0.4.4"

[fs]
"/app" = "."

[[command]]
name = "script"
module = "wasmer/winterjs:winterjs"
runner = "wasi"

[command.annotations.wasi]
main-args = ["/app/wasmer.js"]
